name = "mango"
uuid = "5e49fdec-d473-4d14-b295-7bff2fcf1925"
authors = ["OFFIS e.V."]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
