name: Test Mango.jl

on: [push]


# needed to allow julia-actions/cache to delete caches
permissions:
  actions: write
  contents: read


jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.10', '1']
        julia-arch: [x64]

    steps:
      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
          ports: '1883:1883 8883:8883'
          container-name: 'mqtt'

      - uses: ./github/actions/test_action
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}