name: Test Mango.jl

on: 
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, reopened]


# needed to allow julia-actions/cache to delete caches
permissions:
  actions: write
  contents: read


jobs:
  test_win_mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.10', '1']
        julia-arch: [x64]
        os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN  }}    
          slug: OFFIS-DAI/Mango.jl
          fail_ci_if_error: false

  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.10', '1']
        julia-arch: [x64]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1

      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
          ports: '1883:1883 8883:8883'
          container-name: 'mqtt'

      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN  }}    
          slug: OFFIS-DAI/Mango.jl
          fail_ci_if_error: false
